version: "3.9"

services:
  db:
    image: postgres:15
    container_name: tasks_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./app
    command: >
      sh -c "
      echo 'Waiting for database...';
      sleep 10;
      echo 'Running migrations...';
      alembic -c ./app/alembic.ini upgrade head;
      echo 'Starting FastAPI...';
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
